export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUALITY = "ADJUST_QUALITY";
export const LOAD_CURRENT_DATA = "LOAD_CURRENT_DATA";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_ADJUST_QUALITY = "ADD_ADJUST_QUALITY"
export const Dec_ADJUST_QUALITY = "Dec_ADJUST_QUALITY"
export const IS_LOGIN = "IS_LOGIN"