export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUALITY = "ADJUST_QUALITY";
export const LOAD_CURRENT_DATA = "LOAD_CURRENT_DATA";
export const SET_PRODUCTS = "SET_PRODUCTS";